### ISSUE TITLE
更新安装APK失败

### ISSUE THREAD

**Issue by thkcheng** [starry90/DoubanForAndroid#1]
机型：小米mix3
系统：Android8.0.0
日志1：ActivityManager: startActivity called from non-Activity context; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { act=android.intent.action.VIEW dat=content://com.starry.douban.fileprovider/my_download/db-1.2.5.44-release.apk typ=application/vnd.android.package-archive flg=0x800001 cmp=com.miui.packageinstaller/com.android.packageinstaller.PackageInstallerActivity }
日志2：ActivityTrigger: activityResumeTrigger: not whiteListedcom.starry.douban/com.starry.douban.ui.activity.AppUpdateActivity/25

**Comment by starry90** [comment]
1日志1：是使用Actvity以外的Context启动Actvity需要加Intent.FLAG_ACTIVITY_NEW_TASK

无法打开安装界面原因：在Android 8.0的系统中，未知来源应用权限的开关被移除掉了，取而代之的是未知来源应用的管理列表，如果你想要安装某个被自己所信任的开发者的app,则需要在每一次都手动授权"安装未知应用"的许可。
